// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.25.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'api/bt_api.dart';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class DownloadArgs {
  /// Whether to 'seed' or 'download' the torrent.
  final Mode mode;

  /// The path of the folder where to download file.
  final PathBuf downloadDir;

  /// The path to the torrent metainfo file.
  final PathBuf metainfo;

  /// A comma separated list of <ip>:<port> pairs of the seeds.
  final List<SocketAddr>? seeds;

  /// The socket address on which to listen for new connections.
  final SocketAddr? listen;
  final bool quitAfterComplete;

  const DownloadArgs({
    required this.mode,
    required this.downloadDir,
    required this.metainfo,
    this.seeds,
    this.listen,
    required this.quitAfterComplete,
  });

  @override
  int get hashCode =>
      mode.hashCode ^
      downloadDir.hashCode ^
      metainfo.hashCode ^
      seeds.hashCode ^
      listen.hashCode ^
      quitAfterComplete.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DownloadArgs &&
          runtimeType == other.runtimeType &&
          mode == other.mode &&
          downloadDir == other.downloadDir &&
          metainfo == other.metainfo &&
          seeds == other.seeds &&
          listen == other.listen &&
          quitAfterComplete == other.quitAfterComplete;
}
